<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/cs/tl_news.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * Tschechisch translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Jan Kout (jenda), www.jankout.eu
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_news']['twitter']['0'] = "Zaslat zprávu pomocí Twitteru";
$GLOBALS['TL_LANG']['tl_news']['twitter']['1'] = "Zvolte tuto možnost, chcete-li, abyste zaslali krátkou zprávu také pomocí Twitteru";
$GLOBALS['TL_LANG']['tl_news']['twitterMessage']['0'] = "Zpráva Twitteru";
$GLOBALS['TL_LANG']['tl_news']['twitterMessage']['1'] = "Zadejte sem zprávu, pokud nechcete, aby se převzal počáteční text z ukázky novinky o délce 120 znaků.";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus']['0'] = "Doba, kdy se má daná zpráva odeslat";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus']['1'] = "Zvolte prosím, v jakém časovém horizontu se má daná zpráva odeslat - nyní nebo později (podle nastavení doby zveřejnění). ";
$GLOBALS['TL_LANG']['tl_news']['twitterUrl']['0'] = "Zahrnout odkaz na novinku";
$GLOBALS['TL_LANG']['tl_news']['twitterUrl']['1'] = "Zvolte tuto možnost, chcete-li, aby se ke krátké zprávě přiřadil také odkaz na danou novinku. ";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['now'] = "Odeslat nyní";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['cron'] = "Odeslat podle plánu";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['sent'] = "Zasláno";
$GLOBALS['TL_LANG']['tl_news']['twitter_legend'] = "Twitter";

?>
