<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/cs/explain.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * Tschechisch translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Jan Kout (jenda), www.jankout.eu
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['XPL']['twitter_auth'] = "<p class=\"tl_help_table\">Provázejte Vaší stránku s Vaším účtem Twitteru, je doporučeno, abyste současně zaregistrovali výchozí prohlížeč! Můžete tak učinit na<a href=\"http://dev.twitter.com/apps/new\" onclick=\"window.open(this.href); return false\">http://dev.twitter.com/apps/new</a>.<br /><br /> Ujistěte se jen, že něco zadáte, jinak Twitter vyplní něco jiného.<br /><br />Po úspěšné registraci Vaší stránky zadejte prosím v nastavení systému Contao tzv. \"Consumer key\" a tzv. \"Consumer secret\".</p>";

?>
