<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/cs/modules.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['newstwitter']['0'] = "Novinka";
 
?>
