<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/cs/tl_news_archive.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * Tschechisch translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Jan Kout (jenda), www.jankout.eu
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_news_archive']['twitter']['0'] = "Aktivovat zasílání zpráv pomocí Twitteru";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter']['1'] = "Zaškrtněte tuto možnost, abyste mohli zasílat zprávy na Váš twitterský účet přímo u každé novinky. ";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterAuth']['0'] = "Autorizování Vašeho účtu u Twitteru";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterParams']['0'] = "Parametry internetové adresy";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterParams']['1'] = "Tyto parametry se přidají k odkazu, který se odešle Twitteru. Použijte páry key=value (key1=value1&key2=value2).";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_legend'] = "Twitter";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_ok'] = "Jste přihlášen(á). Klikněte sem pro přihlášení se k jinému kontu.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_error'] = "Autorizace se nezdařila.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_success'] = "Autorizace proběhla úspěšně.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_denied'] = "Autorizace selhala.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_token'] = "Nastala chyba při komunikaci s Twitterem. Prosím zkuste to ještě jednou.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_insecure'] = "Neregistrovali jste Vaši webovou stránku! Je doporučeno provést nejprve tento krok <a href=\"contao/help.php?table=tl_settings&field=twitter_secret\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">Click here for more information.</a>";

?>
