<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/cs/tl_settings.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * Tschechisch translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Jan Kout (jenda), www.jankout.eu 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['twitter_key']['0'] = "Consumer key";
$GLOBALS['TL_LANG']['tl_settings']['twitter_key']['1'] = "<a href=\"contao/help.php?table=tl_settings&field=twitter_key\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">Zadejte prosím tzv. \"Consumer key\".</a>";
$GLOBALS['TL_LANG']['tl_settings']['twitter_secret']['0'] = "Consumer secret";
$GLOBALS['TL_LANG']['tl_settings']['twitter_secret']['1'] = "<a href=\"contao/help.php?table=tl_settings&field=twitter_secret\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">Zadejte prosím \"Consumer secret\".</a>";
$GLOBALS['TL_LANG']['tl_settings']['twitter_legend'] = "Autorizování Vašeho účtu";
 
?>
