<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/ja/explain.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * Japanese translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['XPL']['twitter_auth'] = "<p class=\"tl_help_table\">安全にウェブサイトとTwitterのアカウントをリンクするために、独自の「ブラウザー」のアプリケーションを登録することを<strong>強く</strong>推奨します。これは<a href=\"http://dev.twitter.com/apps/new\" onclick=\"window.open(this.href); return false\">http://dev.twitter.com/apps/new</a>から行えます。<br /><br />コールバックのURLは重要ではありません、ただ何かを提供するかTwitterが「クライアント」のアプリケーションの種類に結果的に機能することを確認してください。<br /><br />アプリケーションの登録に成功した後で、「コンシューマー・キー」と「コンシューマー・シークレット」をシステムの設定に追加してください。</p>";

?>
