<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/ja/tl_news.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * Japanese translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_news']['twitter']['0'] = "Twitterに送信";
$GLOBALS['TL_LANG']['tl_news']['twitter']['1'] = "このニュースをTwitterに送信したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_news']['twitterMessage']['0'] = "Twitterのメッセージ";
$GLOBALS['TL_LANG']['tl_news']['twitterMessage']['1'] = "Twitterに送る更新状況を入力してください。空のままにすると、ニュースのティーザーかメッセージの最初の120文字を使用します。";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus']['0'] = "Twitterの状態";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus']['1'] = "このメッセージを直ちに送信するか、ニュースを公開したあと(の毎時)で送信するか設定してください。この状態はメッセージを送信した後、自動的に一度だけ更新されます。";
$GLOBALS['TL_LANG']['tl_news']['twitterUrl']['0'] = "ニュースのリンクを含める";
$GLOBALS['TL_LANG']['tl_news']['twitterUrl']['1'] = "ニュース項目のURLを含めたい場合に選択してください。URLは http://is.gd/ のサービスを利用して短縮します。";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['now'] = "直ちに送信";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['cron'] = "スケジュール";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['sent'] = "送信済み";
$GLOBALS['TL_LANG']['tl_news']['twitter_legend'] = "Twitter";

?>
