<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/fr/modules.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * French translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['newstwitter']['0'] = "Actualités sur Twitter";
 
?>
