<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/fr/tl_news.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * French translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Cyril Ponce (cyril), http://www.contao.fr
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_news']['twitter']['0'] = "Envoyer sur Twitter";
$GLOBALS['TL_LANG']['tl_news']['twitterMessage']['0'] = "Message Twitter";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus']['0'] = "Statut Twitter";
$GLOBALS['TL_LANG']['tl_news']['twitterUrl']['0'] = "Inclure le lien de l'actualité";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['now'] = "Envoyer maintenant";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['cron'] = "Programmer";
$GLOBALS['TL_LANG']['tl_news']['twitterStatus_ref']['sent'] = "Envoyé";
$GLOBALS['TL_LANG']['tl_news']['twitter_legend'] = "Twitter";

?>
