<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/fr/tl_news_archive.php
 *
 * Contao extension: newstwitter 1.2.0 stable
 * French translation file
 *
 * Copyright : © 2009-2010 Andreas Schempp
 * License   : LGPL
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/
 * Translator: Cyril Ponce (cyril), http://www.contao.fr
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_news_archive']['twitter']['0'] = "Activer Twitter";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterAuth']['0'] = "Autentification Twitter";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterParams']['0'] = "Paramètres URL";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_legend'] = "Twitter";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_error'] = "Vous n'êtes actuellement pas authentifié.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_success'] = "Autentification sur Twitter réussie.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_denied'] = "Autentification sur Twitter interdite.";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_key']['0'] = "Consumer key";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_secret']['0'] = "Consumer secret";

?>
