<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/ja/modules.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['newstwitter']['0'] = "ニュースTwitter";
 
?>
