<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/ja/tl_news_archive.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_news_archive']['twitter']['0'] = "Twitterを使用";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter']['1'] = "選択するとこのニュースアーカイブにTwitterを使用します。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterAuth']['0'] = "Twitter認証";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterParams']['0'] = "URLパラメーター";
$GLOBALS['TL_LANG']['tl_news_archive']['twitterParams']['1'] = "Twitterに送信するURLにパラメーターを追加します。key=valueの組(key1=value1&key2=value2)を使用してください。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_legend'] = "Twitter";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_ok'] = "既に認証済みです。異なる認証情報を使用したい場合はクリックしてください。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_error'] = "現在、認証されていません。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_success'] = "Twitterに認証しました。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_denied'] = "Twitterに認証を拒否されました。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_token'] = "Twitterとの通信中にエラーが起きました。後で再度試してください。";
$GLOBALS['TL_LANG']['tl_news_archive']['twitter_auth_insecure'] = "ウェブサイトをTwitterのアプリケーションとして登録していません! 登録は必須ではありませんが、Twitter認証システムの欠陥の理由から登録を強く推奨します。<a href=\"contao/help.php?table=tl_settings&field=twitter_secret\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">さらに詳しい情報はこちらをクリックしてください。</a>";
 
?>
