<?php
/**
 * TL_ROOT/system/modules/newstwitter/languages/ja/tl_settings.php 
 * 
 * Contao extension: newstwitter 1.2.0 stable 
 * Japanese translation file 
 * 
 * Copyright : © 2009-2010 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['twitter_key']['0'] = "コンシューマー・キー";
$GLOBALS['TL_LANG']['tl_settings']['twitter_key']['1'] = "<a href=\"contao/help.php?table=tl_settings&field=twitter_key\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">あなたのアプリケーションの「コンシューマー・キー」を入力してください。</a>";
$GLOBALS['TL_LANG']['tl_settings']['twitter_secret']['0'] = "コンシューマー・シークレット";
$GLOBALS['TL_LANG']['tl_settings']['twitter_secret']['1'] = "<a href=\"contao/help.php?table=tl_settings&field=twitter_secret\" onclick=\"Backend.openWindow(this, 600, 500); return false;\">あなたのアプリケーションの「コンシューマー・シークレット」を入力してください。</a>";
$GLOBALS['TL_LANG']['tl_settings']['twitter_legend'] = "Twitter認証";
 
?>
